### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by liuyizhuo11235** [lxw15337674/weiboSyncFollow#1]
大大，这种报错怎么处理啊？我查了一下，似乎是因为缓存位置不足，我有一千八百个关注。Uncaught (in promise) DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'followList' exceeded the quota.
    at start (<anonymous>:19:16)

**Comment by lxw404174262** [comment]
哈哈，没考虑到会有这么多关注，等我改下代码

**Comment by lxw15337674** [comment]
![image](https://github.com/lxw15337674/weiboSyncFollow/assets/19898669/cff3db20-6f47-4e41-ac86-569ccdeb5fa9)

这个地方改了下，你试一下可以不。
@liuyizhuo11235

**Comment by liuyizhuo11235** [comment]
万分感谢大佬，问题解决了。另外我觉得文档还可以改进一下，因为我找了好久才发现x-xsrf-token在cookie里面（Chrome浏览器），写明白一点可以方便其他像我这样的小白。

**Comment by lxw15337674** [comment]
> 万分感谢大佬，问题解决了。另外我觉得文档还可以改进一下，因为我找了好久才发现x-xsrf-token在cookie里面（Chrome浏览器），写明白一点可以方便其他像我这样的小白。

哈哈，我加一下截图
