### ISSUE TITLE
关注过快，每次关注30多个后，微博就阻断了，能否减慢关注速度

### ISSUE THREAD

**Issue by fenceiiii** [lxw15337674/weiboSyncFollow#2]
能否减慢关注速度

**Comment by lxw404174262** [comment]
![image](https://github.com/lxw15337674/weiboSyncFollow/assets/111992767/ea45030a-b211-4f33-b4f1-ba324ca64577)
2s一次，按说不快呀，如果要调整，就修改sleep参数，比如10000，对应10s

**Comment by lxw15337674** [comment]
![image](https://github.com/lxw15337674/weiboSyncFollow/assets/19898669/e86d7e8e-a657-45aa-8f1d-1f3272e8a71b)
2s一次，按说不快呀，如果要调整，就修改sleep参数，比如10000，对应10s
