### ISSUE TITLE
方案1与方案2都报403错误，无法成功关注

### ISSUE THREAD

**Issue by WildKid6** [lxw15337674/weiboSyncFollow#3]
如图，还请作者关注，感谢
![image](https://github.com/lxw15337674/weiboSyncFollow/assets/140093375/cbe06297-a22f-4725-93e2-92a1ca9194c6)

**Comment by WildKid6** [comment]
注：已在对应位置填入了XSRF-TOKEN

**Comment by lxw404174262** [comment]
403是拒绝访问，你账号登录的对吗

**Comment by lxw15337674** [comment]
403是拒绝访问，你账号登录的对吗

**Comment by WildKid6** [comment]
是的，严格按照readme指引进行操作的。

按方案2，分别登陆账号A和账号B时，cookie中的XSRF-TOKEN值是一样的，这个是正常的吗？

**Comment by lxw15337674** [comment]
我这是可以的
